#spring.application.name=TODO
#
##spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
#
#spring.datasource.url=jdbc:postgresql://maglev.proxy.rlwy.net:39953/railway
#
##spring.datasource.url=jdbc:postgresql://ep-odd-bread-aty81s7j-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
#
#spring.datasource.username=postgres
#
##spring.datasource.username=neondb_owner
#
##spring.datasource.password=Ganesh@110499
#
#spring.datasource.password=fTIclugClYVrKwZkGNXDQwrNUjhFrKjD
#
#
##spring.datasource.password=npg_JFnph9PzgiU4
#
## PostgreSQL Driver
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## PostgreSQL Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## Server Port (Optional)
##server.port=8080
#
#server.port=${PORT:8080}
#
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#spring.jackson.time-zone=UTC
#
#spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC';
#
#


spring.application.name=TODO

spring.datasource.url=jdbc:postgresql://maglev.proxy.rlwy.net:39953/railway
spring.datasource.username=postgres
spring.datasource.password=fTIclugClYVrKwZkGNXDQwrNUjhFrKjD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

server.port=${PORT:8080}
