spring.application.name=TODO

spring.datasource.url=jdbc:postgresql://localhost:5432/tododb

#spring.datasource.url=jdbc:postgresql://ep-odd-bread-aty81s7j-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=postgres

#spring.datasource.username=neondb_owner

spring.datasource.password=Vinay@2007

#spring.datasource.password=npg_JFnph9PzgiU4

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port (Optional)
server.port=8080